### ISSUE TITLE
file missing

### ISSUE THREAD

**Issue by suravijayjilla** [anudeep-20/Table-extraction-from-PDF-and-Images#1]
Hi,

unable to find python table_extract.py and python extract.py file..
Please update..

**Comment by pcakhilnadh** [comment]
> Hi,
> 
> unable to find python table_extract.py and python extract.py file..
> Please update..

@suravijayjilla  what the version of matplotlib used ?

**Comment by suravijayjilla** [comment]
Hi,

I am using Matplotlib version 3.0.3.

**Comment by anudeep-20** [comment]
@suravijayjilla You can extract the tables in PDF using pdf_extract.py and tables in images using img_extract.py
